name: Afficher le contenu du fichier

on:
  push:
    branches:
      - main

jobs:
  display_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display file content
        run: cat index.html
